services:
  waha:
    container_name: waha
    restart: always
    image: devlikeapro/waha

    logging:
      driver: 'json-file'
      options:
        max-size: '100m'
        max-file: '10'

    ports:
      - '3000:3000/tcp'

    networks:
      - app-network

    volumes:
      # Store sessions in the .sessions folder (comment it if you're using MongoDB)
      - './sessions:/app/.sessions'

      # Save media files
      # https://waha.devlike.pro/docs/how-to/storages/#save-media-files-between-the-container-restarts
      - './media:/app/.media'

    env_file:
      - .env

  valkey:
    image: docker.io/bitnami/valkey:latest
    container_name: valkey
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    command:
      - /opt/bitnami/scripts/valkey/run.sh
      # Load the JSON module
      - --loadmodule
      - "/opt/bitnami/valkey/modules/libjson.so"
      # Keep the password as a single argv token
      - --requirepass
      - "testpass"
      - --appendonly
      - "yes"
      - --save
      - "3600"
      - "1"
      - --save
      - "300"
      - "100"
      - --save
      - "60"
      - "10000"
    volumes:
      - valkey_data:/bitnami/valkey/data
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "valkey-cli -a testpass ping | grep -q PONG" ]
      interval: 2m
      timeout: 5s
      retries: 10
      start_period: 10s
      start_interval: 2s
    restart: unless-stopped

  morning-mailer:
    build:
      context: .
    image: morning-mailer
    container_name: morning-mailer-huey
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    networks:
      - app-network
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./modules:/app/modules
      - ./tasks.py:/app/tasks.py
      - ./gauth:/app/gauth
      - ./users.json:/app/users.json
    command: uv run huey_consumer tasks.huey -k thread -w 1 --flush-locks info
    depends_on:
      valkey:
        condition: service_healthy
    healthcheck:
      test: [
        "CMD-SHELL",
        "python -c \"import os,sys; import redis; r=redis.Redis.from_url(os.getenv('REDIS_URL')); sys.exit(0 if r.ping() else 1)\""
      ]
      interval: 3m
      timeout: 5s
      retries: 3
      start_period: 10s
      start_interval: 2s

#  dozzle-agent:
#    image: amir20/dozzle:latest
#    container_name: dozzle-agent
#    restart: unless-stopped
#    command: agent
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock:ro
#    ports:
#      - "7007:7007" # The default port for Dozzle agents
#    networks:
#      - app-network
#    environment:
#      - DOZZLE_HOSTNAME=Morning-Mailer
#      - DOZZLE_LEVEL=info
#    #      - DOZZLE_FILTER=label=titan-brain
#    healthcheck:
#      test: [ "CMD", "/dozzle", "healthcheck" ]
#      interval: 30s
#      retries: 5
#      start_period: 5s
#      start_interval: 2s

networks:
  app-network:
    driver: bridge

volumes:
  redis-data:
  valkey_data: {}
#  dozzle_data: